/****************************************************************************
 * Platform Abstraction Layer
 * Daryl Borth 2026
 * InputData.h
 *
 * Platform-agnostic input structures
 ***************************************************************************/
#pragma once

#include <cstdint>

/**
 * Universal platform-agnostic button bitmasks
 * Covers Wii, GameCube, and Wii U inputs
 * \ingroup grp_input
 */
enum InputDataButtons : uint32_t {
	INPUT_BTN_NONE    = 0,
	INPUT_BTN_A       = (1 << 0),
	INPUT_BTN_B       = (1 << 1),
	INPUT_BTN_X       = (1 << 2),
	INPUT_BTN_Y       = (1 << 3),
	INPUT_BTN_1       = (1 << 4),
	INPUT_BTN_2       = (1 << 5),
	INPUT_BTN_UP      = (1 << 6),
	INPUT_BTN_DOWN    = (1 << 7),
	INPUT_BTN_LEFT    = (1 << 8),
	INPUT_BTN_RIGHT   = (1 << 9),
	INPUT_BTN_PLUS    = (1 << 10),  // Plus (Wii/Wii U) / Start (GC)
	INPUT_BTN_MINUS   = (1 << 11),  // Minus (Wii/Wii U)
	INPUT_BTN_HOME    = (1 << 12),  // Home (Wii/Wii U)
	INPUT_TRIGGER_L   = (1 << 13),  // L Trigger / Bumper, Nunchuk C
	INPUT_TRIGGER_R   = (1 << 14),  // R Trigger / Bumper
	INPUT_TRIGGER_ZL  = (1 << 15),  // ZL Trigger / GC Z Button, Nunchuk Z
	INPUT_TRIGGER_ZR  = (1 << 16),  // ZR Trigger
	INPUT_THUMB_L     = (1 << 17),  // Left Stick Click (L3)
	INPUT_THUMB_R     = (1 << 18)   // Right Stick Click (R3)
};

//!Hardware profile that a set of button or stick values came from (GameCube, Wiimote, Nunchuk, Classic, Wii U Pro, GamePad).
//!\ingroup grp_input
enum GuiHardwareProfile : uint32_t {
    INPUT_HW_GAMECUBE = 0,
    INPUT_HW_WIIMOTE  = 1,
    INPUT_HW_NUNCHUK  = 2,
    INPUT_HW_CLASSIC  = 3,
    INPUT_HW_WUPC     = 4,
    INPUT_HW_DRC      = 5,
    INPUT_HW_MAX      = 6
};

/**
 * The universal input payload for UI elements.
 * Generated by the driver layer and consumed by GuiElement::update().
 * \ingroup grp_input
 */
struct InputPadData {
	//!\name Unified state
	//!The merged view across every connected profile; for each value the profile with the largest magnitude wins.
	//!@{
	uint32_t buttons_d; //!< Pressed this frame (down)
	uint32_t buttons_h; //!< Held this frame
	uint32_t buttons_r; //!< Released this frame
	float stickX;      //!< Left analog stick X, -1.0 to 1.0
	float stickY;      //!< Left analog stick Y, -1.0 to 1.0
	float substickX;   //!< Right analog stick (C-Stick) X, -1.0 to 1.0
	float substickY;   //!< Right analog stick (C-Stick) Y, -1.0 to 1.0
	float gforceX;     //!< Accelerometer X (Wiimote/Nunchuk/GamePad)
	float gforceY;     //!< Accelerometer Y
	float gforceZ;     //!< Accelerometer Z
	float pitch;       //!< Controller orientation pitch (Wiimote/Nunchuk)
	float roll;        //!< Controller orientation roll
	float yaw;         //!< Controller orientation yaw
	uint32_t battery_level; //!< Controller battery level as reported by the backend
	float cursor_x;     //!< Pointer X on the design canvas (Wiimote IR / GamePad touch)
	float cursor_y;     //!< Pointer Y on the design canvas
	float cursor_angle; //!< Pointer rotation (Wiimote roll)
	bool validPointer;  //!< True if the IR pointer or touch is active on screen
	bool isTouch;       //!< True if input is direct touch (VPad) vs IR pointer
	//!@}

	//!\name Per-hardware-profile state
	//!The same fields as above, indexed by GuiHardwareProfile, so a driver can report e.g. Wiimote buttons and a Nunchuk stick as separate contributors before they are merged.
	//!@{
	bool     hw_connected[INPUT_HW_MAX];   //!< Profile is connected and contributing
	uint32_t hw_buttons_d[INPUT_HW_MAX];   //!< Buttons pressed this frame, per profile
	uint32_t hw_buttons_h[INPUT_HW_MAX];   //!< Buttons held this frame, per profile
	uint32_t hw_buttons_r[INPUT_HW_MAX];   //!< Buttons released this frame, per profile
	float    hw_stickX[INPUT_HW_MAX];      //!< Left stick X, per profile
	float    hw_stickY[INPUT_HW_MAX];      //!< Left stick Y, per profile
	float    hw_substickX[INPUT_HW_MAX];   //!< Right stick X, per profile
	float    hw_substickY[INPUT_HW_MAX];   //!< Right stick Y, per profile

	float    hw_gforceX[INPUT_HW_MAX];     //!< Accelerometer X, per profile
	float    hw_gforceY[INPUT_HW_MAX];     //!< Accelerometer Y, per profile
	float    hw_gforceZ[INPUT_HW_MAX];     //!< Accelerometer Z, per profile
	float    hw_pitch[INPUT_HW_MAX];       //!< Orientation pitch, per profile
	float    hw_roll[INPUT_HW_MAX];        //!< Orientation roll, per profile
	float    hw_yaw[INPUT_HW_MAX];         //!< Orientation yaw, per profile
	//!@}

	InputPadData() {
		buttons_d = buttons_h = buttons_r = 0;
		stickX = stickY = substickX = substickY = 0.0f;
		gforceX = gforceY = gforceZ = 0.0f;
		pitch = roll = yaw = 0.0f;
		battery_level = 0;
		cursor_x = cursor_y = cursor_angle = 0.0f;
		validPointer = isTouch = false;

		for(uint32_t i = 0; i < INPUT_HW_MAX; i++) {
			hw_connected[i] = false;
			hw_buttons_d[i] = hw_buttons_h[i] = hw_buttons_r[i] = 0;
			hw_stickX[i] = hw_stickY[i] = hw_substickX[i] = hw_substickY[i] = 0.0f;
			hw_gforceX[i] = hw_gforceY[i] = hw_gforceZ[i] = 0.0f;
			hw_pitch[i] = hw_roll[i] = hw_yaw[i] = 0.0f;
		}
	}
};
